### ISSUE TITLE
Example in README doesn't seem to run

### ISSUE THREAD

**Issue by grovesNL** [nical/etagere#17]
In the README we have the following example:
```
use etagere::*;

let mut atlas = AtlasAllocator::new(size2(1000, 1000));

let a = atlas.allocate(size2(100, 1000)).unwrap();
let b = atlas.allocate(size2(900, 200)).unwrap();

atlas.deallocate(a.id);

let c = atlas.allocate(size2(300, 200)).unwrap();

assert_eq!(c.rectangle, atlas[c.id]);

atlas.deallocate(c.id);
atlas.deallocate(b.id);
```

There seem to be a couple issues that prevent this from running at the moment.

The first issue is that `assert_eq!(c.rectangle, atlas[c.id]);` fails to compile with
> cannot index into a value of type `etagere::AtlasAllocator

Maybe `impl Index` is meant to be implemented?

The second issue is that the first allocation of `size2(100, 1000)` fails. This seems to happen for any height above `768`, although I didn't expect this to fail because it should fit into `size2(1000, 1000)` as the first rectangle.

I added the README example as an example under `examples/` in this branch if it's helpful: https://github.com/grovesNL/etagere/commit/8cc1a4ac49ce9e52a4d6bb1e921bc4ba90706381 (checkout the commit and run with `cargo run --example atlas`)

**Comment by grovesNL** [comment]
Looks like the example probably came from the `guillotiere` README originally. I noticed the crate documentation uses `size2(100, 100)` for `a` instead, so maybe allocations of `size2(100, 1000)` are expected to fail here. I'd be happy to investigate this more or update the README if this is expected.

**Comment by nical** [comment]
D'oh!

Indeed I totally copied it over from guillotière and forgot to implement the indexing operator. I'll put up a patch soon.

The other issue happens because shelves heights above 512 are rounded up to multiples of 64, which avoids fragmentation but in this situation is a bit silly becuse it rounds something that fits up to something that doesn't. In practice people tend to work with power-of-two texture sizes but it's still surprising so I'll write a fix for it as well.

Thanks for reporting these!
