### ISSUE TITLE
Allocation beyond single column width

### ISSUE THREAD

**Issue by grovesNL** [nical/etagere#26]
We're using `BucketedAtlasAllocator` to create an initial atlas size of 256x256. If we run into a glyph that's wider than 256, we attempt to grow the atlas to 512x512 then find an allocation for that glyph.

When we try to grow the atlas, `grow` keeps the original column width of 256 and instead updates `num_columns` to 2 (512/256): https://github.com/nical/etagere/blob/95d6f376fa85a265fd4493a0bf371777196b33b4/src/bucketed.rs#L154

When we try to find the allocation, this fails at https://github.com/nical/etagere/blob/95d6f376fa85a265fd4493a0bf371777196b33b4/src/bucketed.rs#L172

because `requested_size` (>256) is greater than `column_width` (still 256).

We could set a higher initial atlas size as a temporary work around, but I was wondering what the best path forward might be. Should allocations be able to span multiple columns somehow, or should we try to resize the column width while keeping existing allocations in place?

**Comment by nical** [comment]
In the specific case where we have a single column, we could make it so growing the atlas adds buckets to the existing columns instead of adding a column. 

It is tricky to add more general solutions like letting allocations span multiple columns or having multiple column widths in the same atlas. Both would break some of the simplifying assumptions that make the bucketed allocator work, but I think that the single column thing should address your issue.

As usual I'm short on time so I don't promise adding the feature soon, but I'll be happy to review a PR (and don't hesitate to nag me if I forget to, I'm still sorry about the last one).

Side note: The bucketed allocator is probably not a great fit for allocating very heterogeneous sizes (it will likely suffer from fragmentation to a larger extent than other atlas allocation methods with items of very different sizes). So you may also want to consider:
 - Trying out a different allocator (the non-bucketed will fragment less but does not have a way to grow at the moment, Firefox uses it for its glyph cache).
 - Breaking the texture into multiple allocators so that you can pick a different allocation strategy for very large items.
 - Putting unusually large items into a different texture (Firefox does that).

**Comment by grovesNL** [comment]
Ok great, that sounds reasonable to me. I'll look into implementing that when I get some time.

Thanks for the side note about the heterogeneous allocation problem. For glyphs we generally expect allocations to be relatively homogeneous, but we'll probably end up doing something more sophisticated like texture splitting eventually (e.g., very large font sizes like the case we're running into here).
